spring.application.name=reestr

server.port=8100
server.shutdown=graceful

spring.lifecycle.timeout-per-shutdown-phase=20s

spring.datasource.url=jdbc:postgresql://localhost:5432/itqreestr
spring.datasource.username=postgres
spring.datasource.password=password

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.order_by.default_null_ordering=last

default.page.number=0
default.page.size=10

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.use-fqn=true

api.common.version=1.0.0
api.common.title=Document Registry
api.common.description=API for managing the document registry
api.common.termsOfService=Creates, searches, approves, and coordinates documents
api.common.contact.name=Esipov Aleksey
api.common.contact.url=https://github.com/AlexeyEsipov
api.common.contact.email=a_esipov_it@list.ru




