spring.application.name=util
server.port=8081

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

spring.datasource.url=jdbc:postgresql://localhost:5432/itqreestr
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.order_by.default_null_ordering=last

reestr.url=http://localhost:8100

count.generated.docs=50000
count.batchsize.docs=20
task.max.threads=2

#spring.jpa.properties.hibernate.jdbc.fetch_size=1000

task.executor.pool.size=5
task.executor.pool.core-size=3
task.executor.keepalive.seconds=60
task.executor.queue.capacity=100
task.executor.thread.name-prefix="task-exec-"

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always


springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.use-fqn=true

api.common.version=1.0.0
api.common.title=Batch Utility
api.common.description=API for managing batch documents
api.common.termsOfService=Submit, Approve and Generate Documents
api.common.contact.name=Esipov Aleksey
api.common.contact.url=https://github.com/AlexeyEsipov
api.common.contact.email=a_esipov_it@list.ru



